package simpledb.execution;

import simpledb.storage.Field;
import simpledb.transaction.TransactionAbortedException;
import simpledb.common.DbException;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate p;
    private OpIterator child1;
    private OpIterator child2;

    private TupleDesc td;

    private Tuple t1;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        // wildpea
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        this.td = TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public JoinPredicate getJoinPredicate() {
        // wildpea
        return p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // wildpea
        return child1.getTupleDesc().getFieldName(p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // wildpea
        return child2.getTupleDesc().getFieldName(p.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    @Override
    public TupleDesc getTupleDesc() {
        // wildpea
        return td;
    }

    @Override
    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // wildpea
        child1.open();
        child2.open();
        super.open();
    }

    @Override
    public void close() {
        // wildpea
        child1.close();
        child2.close();
    }

    @Override
    public void rewind() throws DbException, TransactionAbortedException {
        // wildpea
        child1.rewind();
        child2.rewind();
        t1 = null;
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    @Override
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // wildpea
        while (t1 != null || (t1 = findNextT1()) != null) {
            while (child2.hasNext()) {
                Tuple t2 = child2.next();
                if (t1.getField(p.getField1()).compare(p.getOperator(), t2.getField(p.getField2()))) {
                    return mergeTuple(t1, t2);
                }
            }
            child2.rewind();
            t1 = findNextT1();
        }
        return null;
    }

    private Tuple mergeTuple(Tuple t1, Tuple t2) {
        Tuple rt = new Tuple(td);
        int len1 = t1.getTupleDesc().numFields();
        for (int i = 0; i < len1; ++i) {
            rt.setField(i, t1.getField(i));
        }
        for (int i = 0; i < t2.getTupleDesc().numFields(); ++i) {
            rt.setField(i + len1, t2.getField(i));
        }
        return rt;
    }

    private Tuple findNextT1() throws TransactionAbortedException, DbException {
        if (child1.hasNext()) {
            return child1.next();
        } else {
            return null;
        }
    }

    @Override
    public OpIterator[] getChildren() {
        // wildpea
        return new OpIterator[] { child1, child2 };
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // wildpea
        if (children.length >= 1) {
            child1 = children[0];
        }
        if (children.length >= 2) {
            child2 = children[1];
        }
    }

}
